### ISSUE TITLE
undefined error

### ISSUE THREAD

**Issue by ghost** [knadh/niltalk#13]
hello
what is the probleme

 

command-line-arguments
>run.bat
command-line-arguments
.\niltalk.go:91:69: undefined: syscall.SIGUSR1
.\niltalk.go:94:14: undefined: syscall.SIGUSR1

**Comment by scottmeup** [comment]
I encounter "Undefined Error" whenever the hostname as visible to the **client** is not the same as `config.json`:`url`'s value.

If you create an entry in your client's hosts file to point to the IP address of the server, AND set `config.json`:`url`'s value to be that same hostname you may be able to resolve the issue.

**Comment by knadh** [comment]
Apologies. I know it's taken forever, but I've just published a complete rewrite of Niltalk. Please check the repo.
