### ISSUE TITLE
panic(0x3275d8, 0x10804010)

### ISSUE THREAD

**Issue by ghost** [knadh/niltalk#16]
panic: Redis connection failed

goroutine 1 [running]:
panic(0x3275d8, 0x10804010)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x33c
main.main()
        /usr/share/go-1.7/src/github.com/goniltalk/niltalk/niltalk.go:145 +0xbc
exit status 2

I do not understand the error
Someone help me please ??

**Comment by knadh** [comment]
Apologies. I know it's taken forever, but I've just published a complete rewrite of Niltalk. Please check the repo.
