### ISSUE TITLE
added inmemory store and tor support on my fork

### ISSUE THREAD

**Issue by clementauger** [knadh/niltalk#18]
hi,

i made several updates on my fork. Letting you know in case you want to grab some for yourself.

- added in memory store as i really dont care to crash and loose everything and prefer that to run an additional software. Also it makes it a one click to run application, which is what i want. If it was only me the configuration file would be automatically generated at start up with the defaults, i am just not motivated enough for now to implement it.
- added tor support. just set the listen address to tor and it will generate an onion and make things happen. configure the new privatekey option to persist your onion and that's it. Don't forget to empty roolURL too, otherwise it will print unexpected addresses.

see the few commits at https://github.com/clementauger/niltalk/commits/master

I may also add growl support in future, so i can receive desktop notifications when someone speaks or enter a specific room. though i need to figure out a few things at first.

Thanks for that app. Just what i needed.

hth.

**Comment by clementauger** [comment]
it is not an issue.

**Comment by knadh** [comment]
That's quite cool! If you send PRs, these can be merged.

**Comment by clementauger** [comment]
sure. Any guideline here ? Or i just send send pr with all my changes ?

Note few things,
- having tor embedded makes the final executable much bigger (by 10/20Mb i believe), though the end user has really little to do to make his instance available over the tor network.
- unfortunately the embedded tor instance does not automatically updates itself, might be a security issue on a long run

I have added a feature so the user can drag and drop pictures to the chat and it is broadcast to every one on the chan.
basically, there is an extra file store (in memory again), new message type. It is a memory store so the app does not need to write on disk or redis, and the idea is that the image is cached for long time on client side so they dont need to query for it to the server more than once, thus no need to strongly persist on the server side.

edit: ~~note also at some point i might get ride of stuffbin. It just does not handles dev scenario well enough. It lacks a passtrough fs to implement a JIT template parsing that fits dev requirements...~~ done

**Comment by knadh** [comment]
@clementauger no specific guidelines. Just send separate PRs for those features.

Adding 10+ MB to the bin should be alright. Tor support makes sense for the app.

**Comment by clementauger** [comment]
Works for me. I will update later. thanks.
