### ISSUE TITLE
dubious check in redis store

### ISSUE THREAD

**Issue by clementauger** [knadh/niltalk#19]
hey,

in the redis store GetSession method, the statement that verifies that the retrieved handle form redis is not empty is dubious.

In the case the user has not provided an username, which he might do, then the session he opened can never be retrieved.

See this line https://github.com/knadh/niltalk/blob/master/store/redis/redis.go#L164

I have not run manual testing to check for it, though i had to remove the corresponding statement in the memory store i have written.

So i guess this applies to the redis store too.

**Comment by knadh** [comment]
Ah yes. There should not be a session without a handle in the first place. A handle should be auto-generated if one's not specificied here: https://github.com/knadh/niltalk/blob/master/handlers.go#L115
