### ISSUE TITLE
Installation and running

### ISSUE THREAD

**Issue by Fastidious** [knadh/niltalk#3]
Could you expand on the documentation for getting nilktalk running?

**Comment by goniltalk** [comment]
This should help: https://github.com/goniltalk/niltalk/commit/be6aa979c6268c2f53d0e095f4d903a21942a3b8

**Comment by Fastidious** [comment]
Thank you.

Typing `go get github.com/goniltalk/niltalk` creates `bin`, `pkg`, and `src` under my GOPATH. Typing `go get ./...` on my GOPATH adds `autobahn`, `chat`, `example`, and `filematch` to the `bin` directory, already containing a `nilktalk`executable. 

I am assuming that all the git files need to be downloaded and placed somewhere as well, since I do not have `config.json` anywhere.

My order list:
1. Install `go`, set GOPATH
2. Install `redis`
3. Install `websocket`?
4. Run `go get github.com/goniltalk/niltalk`
5. Run `go get ./...` on GOPATH
6. Clone `niltalk` repo (where, on web server path, somewhere else?)
7. Modify config.json to match
8. Run `run` from cloned repo
9. Works?
10. Access it at http://?

**Comment by goniltalk** [comment]
config.json is a part of the Niltalk repo https://github.com/goniltalk/niltalk/blob/master/config.json
1. Install `go`, set GOPATH (assuming eg: /home/user/go)
2. Install and run `redis`
3. Run `go get github.com/goniltalk/niltalk` (this should clone the repo to `/home/user/go/src/github.com/goniltalk/niltalk`)
4. `cd /home/user/go/src/github.com/goniltalk/niltalk` and run `go get ./...` to install dependencies.
5. Edit `/home/user/go/src/github.com/goniltalk/niltalk/config.json`
6. Run `./run` in the same directory
7. Access it on `http://localhost:9000`

**Comment by Fastidious** [comment]
Thanks again! Got it up and running, but upon entering a password, it gives an `Unknown error`. Redis is running on default port and nothing shows on the log (redis) indicating a problem.

**Comment by Fastidious** [comment]
Found the issue. On the `config.json`, the websocket server url must match the hostname. Working now, thanks!
