### ISSUE TITLE
error initializing store: dial tcp: lookup redis on 127.0.0.53:53: server misbehaving

### ISSUE THREAD

**Issue by ghost** [knadh/niltalk#30]
Hi, i have ubuntu 20.04 VPS without white IP.

i want to run niltalk, but i have error:

`ubuntu@ubuntu:~/niltalk_0.1.0_linux_amd64$ ./niltalk`  
`2022/02/13 15:19:45 main.go:82: reading config: config.toml`  
`2022/02/13 15:19:45 error initializing store: dial tcp: lookup redis on 127.0.0.53:53: server misbehaving`  
`ubuntu@ubuntu:~/niltalk_0.1.0_linux_amd64$`  
how to fix this error?

**Comment by ghost** [comment]
on Windows:
![image](https://user-images.githubusercontent.com/20506433/153761028-44db4be4-865b-4d04-9edb-d187697a7f6a.png)

**Comment by knadh** [comment]
Looks like an incorrect `address` param in the Redis `[store]` configuration. If you are running Redis locally, the value should be `address = "127.0.0.1:6379"`

**Comment by ghost** [comment]
what file store these settings? what i need to edit, to work properly?

**Comment by knadh** [comment]
Please read the installation instructions: https://github.com/knadh/niltalk/#manual
