### ISSUE TITLE
Installation of Niltalk?

### ISSUE THREAD

**Issue by ghost** [knadh/niltalk#7]
Hello, I am trying to install niltalk and run it on a test server of mine to tinker around with it. I understand that this hasn't been updated in a while, but I am getting the issue when I try to do `go get github.com/knadh/niltalk` or `go get github.com/goniltalk/niltalk`.
I get the following issue.
`./api.go:286: invalid operation: ctx["token"] (type stack.Context does not support indexing)`

Is there any way to fix this? I'd like to get niltalk up and running on my own host.

**Comment by Vavilen** [comment]
Try to use ctx.Get("token")

**Comment by knadh** [comment]
@myokan It's been over a year now, but turns out, the /stack library's API changed at some point. Niltalk now uses the new API and all the packages have been vendored.
